# Server configuration
server:
  port: 5001
  servlet:
    context-path: /dictionary


# Spring Boot configuration
spring:
  application:
    name: dictionary
  profiles:
    active: development
# Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.bsm.pub:5432/dictionary
    username: bsm_dictionary
    password: bsm_dictionary
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
  output:
    ansi:
      enabled: always
  flyway:
    enabled: false
  jackson:
    default-property-inclusion: non_null

#My batis
mybatis:
  mapper-locations: classpath*:mappers/*.xml

# Logger configuration
logging:
  level:
    org.zalando.logbook: TRACE
    org.springframework.web: DEBUG
    com.bsm: DEBUG
  path: /logs

logbook:
  format.style: http
